name: 删除24小时以前的工作流记录

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜12点执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  delete_old_workflows:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出代码仓库

    - name: Set up Python
      uses: actions/setup-python@v4  # 设置 Python 环境
      with:
        python-version: '3.9'  # 使用 Python 3.9

    - name: Install dependencies
      run: |
        pip install requests  # 安装必要的依赖库

    - name: Run Python script to delete old workflows
      env:
        MY_ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}  # 从 GitHub Secrets 中获取 MY_ACCESS_TOKEN
      run: |
        python main.py  # 运行 Python 脚本
